[package]
name = "passgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_chacha = "0.3.1"
rand = "0.8.5"
zeroize = "1.7.0"
clap = { version = "4.4.18", features = ["derive"] }
